server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/sophy_habits
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
