server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://dpg-cnmq1eo21fec7398cbe0-a/sophy_habits
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
